// Command gendocs writes the CLI reference for the documentation site: one
// Markdown page per command, generated from the same cobra definitions the
// binary uses, so the reference cannot drift from --help.
//
//	go run ./tools/gendocs -out ../provenance-website/content/docs/cli
//
// Output is deterministic: commands are visited in sorted order and nothing
// time- or machine-dependent is written.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/dynamatt/provenance/internal/cli"
)

func main() {
	out := flag.String("out", "", "directory to write the CLI reference into (required)")
	flag.Parse()
	if *out == "" || flag.NArg() > 0 {
		fmt.Fprintln(os.Stderr, "usage: gendocs -out <dir>")
		os.Exit(2)
	}
	if err := write(*out, generate(cli.NewRootCmd())); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(2)
	}
}

// write replaces every generated page in dir with pages. Only .md files are
// removed first, so a page for a deleted command does not linger.
func write(dir string, pages map[string]string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	old, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	for name, content := range pages {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

const generatedNote = "# Generated by tools/gendocs in github.com/dynamatt/provenance. Do not edit."

// generate returns file name -> content for the section index and every
// command below root.
func generate(root *cobra.Command) map[string]string {
	// cobra adds these lazily at execution time; add them now so they are listed.
	root.InitDefaultHelpFlag()
	root.InitDefaultVersionFlag()
	cmds := commands(root)
	pages := map[string]string{"_index.md": index(root, cmds)}
	for i, c := range cmds {
		pages[fileName(c)+".md"] = page(c, (i+1)*10)
	}
	return pages
}

// commands lists every command below root, depth-first in name order (cobra
// sorts subcommands by name), without the built-in help command.
func commands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			if sub.Name() == "help" || sub.Hidden {
				continue
			}
			out = append(out, sub)
			walk(sub)
		}
	}
	walk(root)
	return out
}

// name is the command path without the binary name, e.g. "sign verify".
func name(c *cobra.Command) string {
	return strings.TrimPrefix(c.CommandPath(), c.Root().Name()+" ")
}

func fileName(c *cobra.Command) string { return strings.ReplaceAll(name(c), " ", "-") }

func ref(c *cobra.Command) string {
	return fmt.Sprintf("[`%s`]({{< relref \"%s.md\" >}})", name(c), fileName(c))
}

// isGroup reports whether c only holds subcommands.
func isGroup(c *cobra.Command) bool { return c.HasAvailableSubCommands() && cli.Implemented(c) }

func status(c *cobra.Command) string {
	switch {
	case !cli.Implemented(c):
		return "Not yet implemented"
	case isGroup(c):
		return "—"
	default:
		return "Available"
	}
}

func index(root *cobra.Command, cmds []*cobra.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\n%s\ntitle: \"CLI reference\"\ndescription: %q\nbookCollapseSection: true\n---\n\n",
		generatedNote, "Every provenance command, its arguments and flags.")
	b.WriteString("Every command of the `" + root.Name() + "` binary, generated from the same\n")
	b.WriteString("definitions as its `--help` output. Commands marked *Not yet implemented*\n")
	b.WriteString("are part of the planned command surface: in the current build they print\n")
	b.WriteString("`<command>: not implemented yet` and exit with code 2.\n\n")

	b.WriteString("## Commands\n\n| Command | Description | Flags | Status |\n| --- | --- | --- | --- |\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", ref(c), cell(c.Short), flagNames(c), status(c))
	}

	b.WriteString("\n## Exit codes\n\n")
	b.WriteString("Exit codes are the only guaranteed contract for CI.\n\n")
	b.WriteString("| Code | Meaning |\n| --- | --- |\n")
	b.WriteString("| `0` | Success |\n")
	b.WriteString("| `1` | Expected failure reported: violations found, hash or signature mismatch, gate blocked |\n")
	b.WriteString("| `2` | Tool or usage error: bad arguments, missing file, unreadable repository |\n")

	b.WriteString("\n## Global flags\n\n")
	flagTable(&b, root.Flags())
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func page(c *cobra.Command, weight int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\n%s\ntitle: %q\ndescription: %q\nweight: %d\n---\n\n",
		generatedNote, name(c), c.Short, weight)

	if !cli.Implemented(c) {
		fmt.Fprintf(&b, "> **Not yet implemented.** In the current build this command prints\n"+
			"> `%s: not implemented yet` and exits with code 2.\n\n", name(c))
	}

	b.WriteString("## Usage\n\n```text\n")
	if c.Runnable() && !isGroup(c) {
		b.WriteString(c.UseLine() + "\n")
	}
	if c.HasAvailableSubCommands() {
		b.WriteString(c.CommandPath() + " <command>\n")
	}
	b.WriteString("```\n\n")

	desc := c.Long
	if desc == "" {
		desc = c.Short + "."
	}
	b.WriteString(prose(desc))

	if c.HasAvailableSubCommands() {
		b.WriteString("## Commands\n\n| Command | Description |\n| --- | --- |\n")
		for _, sub := range c.Commands() {
			if sub.IsAvailableCommand() {
				fmt.Fprintf(&b, "| %s | %s |\n", ref(sub), cell(sub.Short))
			}
		}
		b.WriteString("\n")
	}

	if hasFlags(c.LocalFlags()) {
		b.WriteString("## Flags\n\n")
		flagTable(&b, c.LocalFlags())
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// flagNames lists c's own flags for the index, e.g. "`--scope`, `--out`".
func flagNames(c *cobra.Command) string {
	var names []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if !f.Hidden && f.Name != "help" {
			names = append(names, "`--"+f.Name+"`")
		}
	})
	if len(names) == 0 {
		return "—"
	}
	return strings.Join(names, ", ")
}

func hasFlags(fs *pflag.FlagSet) bool {
	has := false
	fs.VisitAll(func(f *pflag.Flag) { has = has || (!f.Hidden && f.Name != "help") })
	return has
}

// flagTable writes fs (in name order, without --help) as a Markdown table.
func flagTable(b *strings.Builder, fs *pflag.FlagSet) {
	b.WriteString("| Flag | Default | Description |\n| --- | --- | --- |\n")
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		varname, usage := pflag.UnquoteUsage(f)
		flag := "--" + f.Name
		if f.Shorthand != "" {
			flag = "-" + f.Shorthand + ", " + flag
		}
		if varname != "" && f.Value.Type() != "bool" {
			flag += " " + varname
		}
		def := "—"
		if f.DefValue != "" && f.DefValue != "false" {
			def = "`" + f.DefValue + "`"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", flag, def, cell(usage))
	})
	b.WriteString("\n")
}

// prose turns help text (hard-wrapped paragraphs separated by blank lines)
// into Markdown paragraphs. Flags, paths and file names become code spans, so
// neither Markdown nor the site's typographer (which turns "--" into a dash)
// alters them; everything else has Markdown syntax escaped.
func prose(s string) string {
	var b strings.Builder
	for _, para := range strings.Split(strings.TrimSpace(s), "\n\n") {
		words := strings.Fields(para)
		for i, w := range words {
			words[i] = proseWord(w)
		}
		b.WriteString(strings.Join(words, " ") + "\n\n")
	}
	return b.String()
}

func proseWord(w string) string {
	core := strings.TrimLeft(w, "(")
	lead := w[:len(w)-len(core)]
	trimmed := strings.TrimRight(core, ".,;:)")
	trail := core[len(trimmed):]
	if isLiteral(trimmed) {
		return escape(lead) + "`" + trimmed + "`" + escape(trail)
	}
	return escape(w)
}

// isLiteral reports whether a word must appear verbatim: a flag (--scope), a
// dot-file or path (./_site, .provenance-export, schema/), or a snake_case name.
func isLiteral(w string) bool {
	return strings.HasPrefix(w, "--") || strings.HasPrefix(w, ".") ||
		strings.HasSuffix(w, "/") || strings.Contains(w, "_")
}

func cell(s string) string { return strings.ReplaceAll(escape(s), "|", `\|`) }

var escaper = strings.NewReplacer(
	`\`, `\\`, "`", "\\`", "*", `\*`, "_", `\_`,
	"[", `\[`, "]", `\]`, "<", "&lt;", ">", "&gt;",
)

func escape(s string) string { return escaper.Replace(s) }
